<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    </head>
    <body class="container" style="background-color: #DEDEDE">
        <section class="row mt-5">
            <div class="col-md-4 offset-md-4">
                <div class="card card-body">
                    <form action="" method="post">
                        <input name="email" placeholder="Email" type="text" class="form-control mb-3">
                        <input name="password" placeholder="Senha" type="password" class="form-control mb-3">

                        <div class="d-grid">
                            <button class="btn btn-primary">ENTRAR</button>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </body>
</html>