<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

        <title>Document</title>

    </head>
    <body style="background-color: #DEDEDE;" class="container">
        <section class="mt-5 card card-body">
            <h1>Administrar Perfis de Usuários</h1>

            <p class="alert alert-info">
                Bem vindo(a) <?php echo $_SESSION['user_logged']['name']; ?>

                <a href="/logout" class="btn btn-danger btn-sm ms-3">Sair</a>
            </p>

            

            <hr>

            <table class="table table-striped table-hover">
                <thead class="table-dark">
                    <tr>
                        <th>#ID</th>
                        <th>Nome</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody id="tabela">
                    <?php
                        foreach ($roles as $role) {
                            echo "<tr>
                                <td>{$role->id}</td>
                                <td>{$role->name}</td>
                            </tr>";
                        }
                    ?>

                </tbody>
            </table>
        </section>

        <!-- <script>
            fetch ('http://localhost:8000/roles')
                .then(res => res.json())
                .then(dados => dados.map(x => {
                    tabela.innerHTML += `
                        <tr>
                            <td>${x.id}</td>
                            <td>${x.name}</td>
                        </tr>
                    `;
                }));

        </script> -->
    </body>
</html>